import type { ModuleManifest } from '@freebbs-development/contracts';

export const MODULE_MANIFESTS: readonly ModuleManifest[] = [
  {
    id: 'dashboard',
    name: '工作台',
    description: '汇总平台入口、动态与待办。',
    route: '/dashboard',
    icon: 'dashboard',
    ownerTeam: 'platform-core',
    status: 'enabled',
    requiredPermissions: ['dashboard.read'],
    order: 10,
  },
  {
    id: 'knowledge',
    name: '经验库',
    description: '沉淀流程、问答、联系人和活动复盘。',
    route: '/knowledge',
    icon: 'knowledge',
    ownerTeam: 'platform-core',
    status: 'enabled',
    requiredPermissions: ['knowledge.read'],
    order: 20,
  },
  {
    id: 'information',
    name: '信息与咨询',
    description: '发布透明信息并承接同学咨询。',
    route: '/information',
    icon: 'information',
    ownerTeam: 'liaison-rights',
    status: 'enabled',
    requiredPermissions: ['information.announcement.read'],
    order: 30,
  },
  {
    id: 'clubs',
    name: '社群与俱乐部',
    description: '建设和维护学生社群与俱乐部。',
    route: '/clubs',
    icon: 'clubs',
    ownerTeam: 'arts',
    status: 'enabled',
    requiredPermissions: ['clubs.read'],
    order: 40,
  },
  {
    id: 'events',
    name: '活动',
    description: '规范活动创建、报名与复盘流程。',
    route: '/events',
    icon: 'events',
    ownerTeam: 'cross-domain',
    status: 'enabled',
    requiredPermissions: ['events.read'],
    order: 50,
  },
  {
    id: 'liaison',
    name: '联络资源',
    description: '维护公开、组织内与受限联络资源。',
    route: '/liaison',
    icon: 'liaison',
    ownerTeam: 'liaison',
    status: 'enabled',
    requiredPermissions: ['liaison.resource.read'],
    order: 60,
  },
  {
    id: 'sports',
    name: '体育代表队',
    description: '管理代表队、队员和训练签到。',
    route: '/sports',
    icon: 'sports',
    ownerTeam: 'sports',
    status: 'enabled',
    requiredPermissions: ['sports.team.read'],
    order: 70,
  },
  {
    id: 'finance',
    name: '财务治理',
    description: '以可审计方式管理预算与结算。',
    route: '/finance',
    icon: 'finance',
    ownerTeam: 'rights-development',
    status: 'enabled',
    requiredPermissions: ['finance.record.read'],
    order: 80,
  },
  {
    id: 'admin',
    name: '权限与模块管理',
    description: '管理模块、角色、标签与审计记录。',
    route: '/admin',
    icon: 'admin',
    ownerTeam: 'platform-core',
    status: 'enabled',
    requiredPermissions: ['admin.manage'],
    order: 90,
  },
] as const;
